### ISSUE TITLE
"Losing" Journeymap Data

### ISSUE THREAD

**Issue by TripleChaos** [Brycey92/Galaxy-Craft-Issues#37]
**Pack version**
1.0.3

**Describe the bug**
Connecting to the server through the button in the main menu puts Journeymap data into another folder than when connecting to the server through the multiplayer button in the main menu, resulting in a different map for both ways of connecting

**To reproduce**
Pretty self-explanatory in the description

**Expected behavior**
Journeymap data should be put in the same folder, regardless of how a player connects

**Comment by Brycey92** [comment]
Unfortunately, the issue I thought this was - the Multiplayer menu having a different IP than the main menu button - isn't it, because both point to the same IP in the pack's zip file, and those files are overwritten every pack update. This will require more investigation.

**Comment by Brycey92** [comment]
It appears that when you play through the multiplayer menu, Journeymap saves images to the journeymap/mp/Galaxy\~Craft\~Lite folder, but when you play through the main menu, it saves to the journeymap/mp/offline folder.

**Comment by Brycey92** [comment]
It turns out this is because Custom Main Menu just gives the client `null` as the server name, instead of actually allowing it to be input from the menu config or something. Thus, when Journeymap checks the server name and finds that it doesn't exist, it assumes the user is playing offline.

I spent 2 days decompiling and recompiling Custom Main Menu to add a config option for a server name, and it has been tested and confirmed to be working by @WillKracke.
